### ISSUE TITLE
Announcements should be signed

### ISSUE THREAD

**Issue by waldheinz** [syncthing/specs#12]
Currently, the discovery protocol is susceptible to DOS attacks where a malicious entity would send bogus announcements to the central discovery server, thus overriding potentially valid information previously stored there.

A remedy could be to have the clients sign their announcements, and the discovery server would silently discard announcements not carrying a valid signature. The details of this would still have to be worked out, especially if the device id that is already part of the announcement carries enough information about the sending device to actually validate a signature.

Implementing this would still allow an attacker to employ replay attacks, though. To remedy this it might be sufficient to include either a serial number or timestamp in the announcement, where the timestamp seems preferable because it would not mean that the client needs to keep track of additional state beyond what it already does. The announcement server would again silently discard messages carrying a timestamp that is too far off the server's clock. Obviously, this would imply that client and server clocks are in sync. I have no insight if this is still a problem these days, where almost every OS / device employs NTP time synchronization by default. Probably not?

**Comment by calmh** [comment]
We'd need to include the following in the announcement:

 - The announcement
 - The new timestamp
 - The signature
 - The certificate itself

We then check that the timestamp is reasonable, that the signature matches the certificate, and that the hash of the certificate matches the device ID in the announcement.

That all should fit in under 1500 bytes, but it'll be significantly larger than currently and might result in fragmentation and MTU issues. I don't know how big/common those issues would be though.

**Comment by waldheinz** [comment]
>  and that the hash of the certificate matches the device ID in the announcement

I think this part could be skipped, because the hash of the certificate would no longer need to be part of the announcement. When the server decides that the signature matches the certificate, it can calculate the hash himself. I have no clue how big the certificate is, could you give a number?

Maybe it's also due to think if this opens the doors for DoS attacks against the server, where it's only busy verifying signatures of bogus announcements, and not doing any useful work.

But swamping the server with bogus announcements is also possible with the protocol as-is, so at least the situation is not getting worse. :-)

**Comment by calmh** [comment]
Fair enough, device ID doesn't need to be there explicitly any more.

My certificate is 994 bytes (after PEM decoding). A current advertisement clocks in around 80 bytes. A signature is about the same size as the key modulus (I think, we should check this) which in our case means around 3072 bits (384 bytes). So that's about 1378 bytes of cert+sig. Just keeping to ethernet MTU (1472 bytes plus overhead) that gives us about 94 bytes of space for actual data.

**Comment by waldheinz** [comment]
Having only ~100 bytes for the actual payload is unfortunate, as it might limit possible extensions in the future. Maybe it's best to explore whether it's possible to utilize a HMAC for our purposes. The client tucking on a SHA256 based MAC would cost only 256 bytes and leave plenty of room to do something useful.

Problem is that client and server would have to agree on a shared secret to make this possible. Stateless key exchange sounds like an oxymoron to me, but I'll try to investigate this route later today when I'll have a lengthy trip where I hopefully won't be the driver. :-)

**Comment by calmh** [comment]
Yeah, another option is to use actual TLS to do the announcement and so on. Just need to be somewhat careful so we don't hammer the servers to death in the process.

**Comment by AudriusButkevicius** [comment]
I don't think we can bet on fitting something into a single MTU, due to relay addresses going in, IP's becoming URLs with arbitrary amounts of information being advertised, etc.
Also the above UDP based solution is prone to even tiny clock skew or alternatively replay attacks if the window is big.

I feel that TLS is the only way forward.
You can load balance just by having a shared SQL backend, so it's already scalable to some extent.

**Comment by waldheinz** [comment]
An clock window of maybe 30 seconds would mean that a replay "attack" would most probably replay data that is still valid, thus doing no harm at all. But I agree that TLS would probably the simplest thing to do, given that I have little experience dealing with cryptographic primitives directly its also the only thing I can consider "safe", though other people may have a more informed opinion about this.
Am 11.09.2015 8:38 nachm. schrieb Audrius Butkevicius <notifications@github.com>:I don't think we can bet on fitting something into a single MTU, due to relay addresses going in, IP's becoming URLs with arbitrary amounts of information being advertised, etc.
Also the above UDP based solution is prone to even tiny clock skew or alternatively replay attacks if the window is big.

I feel that TLS is the only way forward.
You can load balance just by having a shared SQL backend, so it's already scalable to some extent.

**Comment by calmh** [comment]
We've almost already bought into having an established tls connection to every device out there with the relay service (assuming a small number of standard relays), so yeah, this is doable.

**Comment by calmh** [comment]
Or, well, it doesn't need to be kept established of course. If we use the normal https framework, keepalive connections should aggregate some stuff for us though so that we don't keep opening and closing connections for every query.
