### ISSUE TITLE
Why are Message IDs necessary?

### ISSUE THREAD

**Issue by vikstrous** [syncthing/specs#13]
The communication is over TCP, so there is no possibility of losing packets. The sender doesn't need a Message ID to know which message the response is for because they know what order the messages were sent in. Since the receiver is not allowed to answer out of order, the server can easily figure out which message they are replying to. Are there messages for which the sender doesn't know if there will be a reply?

**Comment by vikstrous** [comment]
On a related note, why is the size of the uncompressed data included in compressed messages? To make it easier to pre-allocate memory in languages where this is hard, like C? It's not actually necessary because the size of the uncompressed data is known. The Go LZ4 implementation even has a stream reader/writer.

**Comment by AudriusButkevicius** [comment]
The dispach is async, it can take a while for us to respond, and we can't guarantee we weill reply in order as each request can be in its own "thread". The size question, even in Go we try to reuse memory, so we need to know if thr block we have is sufficient there.

**Comment by AudriusButkevicius** [comment]
And the stream thing does not work as you'd have remalloc on every byt euntil EOF.

**Comment by vikstrous** [comment]
From the spec:
`Responses MUST however be sent in the same order as the requests are received.`

Is this not correct or am I misunderstanding something? If the sender keeps track of all requests in one place somehow (and they must for allocating message ids), then that central place can route the responses to whichever thread made the requests can't it?

The memory allocation thing makes sense. Thanks.

**Comment by AudriusButkevicius** [comment]
Right, no clue why that's there, neither I know if we satisfy that. I know some messages have order, such as clusterconfig before anything else, etc.

**Comment by calmh** [comment]
I think that's spec a bug. Given that sentence, there would be no need for message ID:s. We certainly don't enforce that, and if we even follow it it's probably just by chance. I suspect it's wildly incorrect and should be removed.
